platform :ios, '9.0'

target 'LightControl' do
  use_frameworks!

  pod 'SwifterSwift'
  pod 'AutoInch'
  pod 'SnapKit'
  pod 'YXAlertController'
  pod 'SwiftyBluetooth'
  pod 'Toast-Swift', '~> 5.0.1'

end
